### ISSUE TITLE
Elasticsearch: Datetime parsing

### ISSUE THREAD

**Issue by Backenkoehler** [codeformuenster/open-events#5]
Elasticsearch hat Probleme beim parsen der Datetime vom MS Scraper

`[2015-06-03 18:20:28,333][DEBUG][action.bulk              ] [Ocean] [logstash-2015.06.03][1] failed to execute bulk item (index) index {[logstash-2015.06.03][kultur][AU26py8tKYacee6wJVKZ], source[{"parsedate":"Donnerstag, 2.7.2015","datetime":"2015-07-02 20:00","type":"kultur","parsetime":"18 - 20 Uhr","title":"Zeichnen vs. Illustration   -   Workshop für Anfänger und Fortgeschrittene","md5":"c98665f253407e3cf612f1c740335d58","link":"http://www.lwl.org/lwlkalender/VeranstaltungAction.do?id=1035527","location_id":"3","@version":"1","@timestamp":"2015-06-03T18:20:27.124Z","host":"172.17.0.104"}]}
elasticsearch_1     | org.elasticsearch.index.mapper.MapperParsingException: failed to parse [datetime]
elasticsearch_1     |     at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:409)
elasticsearch_1     |     at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:706)
elasticsearch_1     |     at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:497)
elasticsearch_1     |     at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:544)
elasticsearch_1     |     at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:493)
elasticsearch_1     |     at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:453)
elasticsearch_1     |     at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:432)
elasticsearch_1     |     at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:149)
elasticsearch_1     |     at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:515)
elasticsearch_1     |     at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:422)
elasticsearch_1     |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
elasticsearch_1     |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
elasticsearch_1     |     at java.lang.Thread.run(Thread.java:745)
elasticsearch_1     | Caused by: org.elasticsearch.index.mapper.MapperParsingException: failed to parse date field [2015-07-02 20:00], tried both date format [dateOptionalTime], and timestamp number with locale []
elasticsearch_1     |     at org.elasticsearch.index.mapper.core.DateFieldMapper.parseStringValue(DateFieldMapper.java:619)
elasticsearch_1     |     at org.elasticsearch.index.mapper.core.DateFieldMapper.innerParseCreateField(DateFieldMapper.java:547)
elasticsearch_1     |     at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:236)
elasticsearch_1     |     at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:399)
elasticsearch_1     |     ... 12 more
elasticsearch_1     | Caused by: java.lang.IllegalArgumentException: Invalid format: "2015-07-02 20:00" is malformed at " 20:00"
elasticsearch_1     |     at org.elasticsearch.common.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:187)
elasticsearch_1     |     at org.elasticsearch.common.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:780)
elasticsearch_1     |     at org.elasticsearch.index.mapper.core.DateFieldMapper.parseStringValue(DateFieldMapper.java:613)
elasticsearch_1     |     ... 15 more`

**Comment by tomsrocket** [comment]
Ich close diesen task, um mal zu sehen wie geschlossene Tasks in der Github API aussehen. :-)
